# Generated by Django 2.1.2 on 2018-10-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        ('trunk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trunk_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.Trunk')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
    ]
