# Generated by Django 2.1.2 on 2018-10-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
    ]
