# Generated by Django 2.1.2 on 2018-10-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('hex_color', models.CharField(max_length=6)),
                ('trunk_lenght', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pre_trunk_lenght', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
