# Generated by Django 2.1.2 on 2018-10-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('hex_color', models.CharField(max_length=6)),
                ('trunk_lenght', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pre_trunk_lenght', models.DecimalField(decimal_places=3, max_digits=10)),
                ('begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='stations.Station')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='stations.Station')),
            ],
        ),
    ]
