# Generated by Django 2.1.2 on 2018-10-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0003_auto_20181003_0216'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='trunk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trunk.Trunk'),
            preserve_default=False,
        ),
    ]
