# Generated by Django 2.1.2 on 2018-10-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trunk', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.Sector')),
                ('trunk', models.ManyToManyField(to='trunk.Trunk')),
            ],
        ),
    ]
